---
  - name: Setup git
    hosts: localhost
    connection: local
    tasks:
      - name: Ensure git is installed
        ansible.builtin.apt:
          name: 
      - git
    state: present
    update_cache: true

  - name: Set editor
    ansible.builtin.git_config:
      name: core.editor
      scope: global
      value: vim

  - name: Fix Git_install
    ansible.builtin.git_config:
      name: init.defaultBranch
    scope: global
    value: main

  - name: Add Git alias for log
    ansible.builtin.git_config:
      name: alias.lol
      scope: global
      value: "log --graph --decorate --oneline --all"

  - name: Set Git username
    ansible.builtin.git_config:
      name: user.name
      scope: global
      value: "{{ git_user }}"

  - name: Set Git email
    ansible.builtin.git_config:
      name: user.email
      scope: global
      value: "{{ git_email }}"

