---
- name: Update apt packages
  tags:
    - update_packages
  block:

    - name: Install core packages
      ansible.builtin.apt:
        name:
          - xfce4-panel
          - picom
          - thunar
          - thunar-archive-plugin
          - ufw
          - xfce4-terminal
          - xfce4-notifyd
          - xfce4-pulseaudio-plugin
          - xfce4-power-manager
          - rofi
          - flameshot
          - git
          - vim
          - net-tools
          - bluez
          - blueman
          - i3
          - lightdm
          - x2goserver
          - x2goserver-xsession
          - python3
          - npm
          - nitrogen
          - zoxide
          - lxappearance
          - breeze-cursor-theme
          - curl
          - fzf
          - htop
          - nala
          - pass
          - s-tui
          - pulseeffects
          - tmux
          - vlc
          - shotwell
          - xarchiver
          - xclip
          - cifs-utils
          - gvfs-backends
          - golang-go
          - tree
          - adwaita-icon-theme
        state: present
        update_cache: true

    - name: Purge old notification app
      ansible.builtin.apt:
        name:
          - dunst
        state: absent
