---
- name: Update apt packages
  tags:
    - update_packages
  block:

    - name: Install sudo
      ansible.builtin.apt:
        name: sudo
        state: present

    - name: Add i386 Architecture
      ansible.builtin.command: dpkg --add-architecture i386
      changed_when: true
      become: true


    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Try to install each package
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - picom
          - thunar
          - speech-dispatcher
          - thunar-archive-plugin
          - ufw
          - xfce4-terminal
          - rofi
          - flameshot
          - git
          - vim
          - net-tools
          - bluez
          - blueman
          - polybar
          - i3
          - lightdm
          - python3
          - npm
          - nitrogen
          - zoxide
          - lxappearance
          - breeze-cursor-theme
          - curl
          - fzf
          - htop
          - nala
          - pass
          - s-tui
          - pulseeffects
          - tmux
          - vlc
          - shotwell
          - xarchiver
          - xclip
          - cifs-utils
          - gvfs-backends
          - golang-go
          - tree
          - adwaita-icon-theme
          - ranger
          - arandr
            # - libpango1.0-dev
#          - libc6:amd64
#          - libc6:i386
#          - libegl1:amd64
#          - libegl1:i386
#          - libgbm1:amd64
#          - libgbm1:i386
#          - libgl1-mesa-dri:amd64
#          - libgl1-mesa-dri:i386
#          - libgl1:amd64
#          - libgl1:i386
#          - libnvidia-ngx1
#          - nvidia-driver-libs:i386
#          - steam-libs-amd64:amd64
          - neofetch
          - python3-pip
          - pasystray
          - speedtest-cli
      become: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
      become: true
