---
- name: Create symlink for .bash_aliases
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/user/files/.bash_aliases"
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Create symlink for .bash_profile
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/user/files/.bash_profile"
    dest: "/home/{{ ansible_user }}/.bash_profile"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Ensure .bashrc sources .bash_aliases
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi'
    state: present

- name: Ensure .bashrc sources .bash_profile
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi'
    state: present

- name: Source bash files
  ansible.builtin.shell:
    cmd: |
      source /home/{{ ansible_user }}/.bash_aliases
      source /home/{{ ansible_user }}/.bash_profile
      source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash
  changed_when: true
