---
- name: Create symlink for .bash_aliases
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/user/files/.bash_aliases"
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Create symlink for .bash_rc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/user/files/.bashrc"
    dest: "/home/{{ ansible_user }}/.bashrc"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Source bash files
  ansible.builtin.shell:
    cmd: |
      source /home/{{ ansible_user }}/.bash_aliases
      source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash
  changed_when: true
