---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable ALL mount unit files
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ lookup('fileglob', '{{ playbook_dir }}/roles/systemd/file/mounts/*.mount', wantlist=True) | map('basename') }}"
  loop_control:
    loop_var: item
  tags:
    - full_install
    - all_sysd_mounts
