---
- name: Ensure git is installed
  ansible.builtin.apt:
    name:
      - git
    state: present
    update_cache: true
  become: true

- name: Set editor
  ansible.builtin.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Name main branch
  ansible.builtin.git_config:
    name: init.defaultBranch
    scope: global
    value: meow

- name: Add Git alias for log
  ansible.builtin.git_config:
    name: alias.lol
    scope: global
    value: "log --graph --decorate --oneline --all"

- name: Set Git username
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "{{ git_user }}"

- name: Set Git email
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
