---
- name: Link Helper scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/helper-scripts/"
    dest: "home/{{ ansible_user }}/tools/helper-scripts/"
    state: link
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
