---
- name: Link tool scripts
  tags:
    - link_scripts
  block:
    - name: Ensure tools dir exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/tools/"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Link Helper scripts
      ansible.builtin.file:
        src: "{{ role_path }}/files/helper-scripts"
        dest: "/home/{{ ansible_user }}/tools/helper-scripts"
        state: link
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Make git script callable from anywhere
      ansible.builtin.file:
        src: "/home/{{ ansible_user }}/tools/helper-scripts/gcp.sh"
        dest: "/usr/local/bin/gcp.sh"
        state: link
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: true
