---
# tasks file for user-apps
- name: Setup git
  ansible.builtin.include_tasks: git.yml

- name: Set tmux
  ansible.builtin.include_tasks: tmux.yml

- name: Set i3
  ansible.builtin.include_tasks: i3.yml

- name: Set picom
  ansible.builtin.include_tasks: picom.yml
