---
- name: Ensure tmux is installed
  ansible.builtin.apt:
    name:
      - tmux
    state: present
    update_cache: true
  become: true

- name: Installed TPM
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ ansible_user }}/.tmux/plugins/"
    update: true
    clone: true
  ignore_errors: true
  tags:
    skip_ansible_lint

- name: Copy tmux.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/user-apps/files/.tmux.conf"
    dest: "/home/{{ ansible_user }}/.tmux.conf"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
