---
- name: Configure Lightdm
  tags:
    - lightdm
  block:

    - name: Set background color in lightdm-gtk-greeter.conf
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm-gtk-greeter.conf
        regexp: '^background='
        line: 'background=#3D3846'
        state: present
      become: true

    - name: Set theme in lightdm-gtk-greeter.conf
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm-gtk-greeter.conf
        regexp: '^theme-name='
        line: 'theme-name=Adwaita-dark'
        state: present
      become: true
