---
- name: Check if neovim is installed
  tags:
    - update
  block:
    - name: Check if neovim is installed
      ansible.builtin.command:
        cmd: ls /usr/local/bin/nvim
      register: is_installed
      changed_when: true
      ignore_errors: true

    - name: Check neovim version
      ansible.builtin.command:
        cmd: nvim --version
      when: is_installed.rc == 0
      changed_when: true
      register: result

    - name: Get Current Version
      ansible.builtin.set_fact:
        current_version: "{{ result.stdout.split()[1] }}"
      when: is_installed.rc == 0

    - name: Get latest version from github
      ansible.builtin.uri:
        url: https://api.github.com/repos/neovim/neovim/releases/latest
        method: GET
        return_content: true
      register: repo_info
      when: is_installed.rc == 0

    - name: Extract latest tag name
      ansible.builtin.set_fact:
        latest_tag: "{{ repo_info.json.tag_name }}"
      when: is_installed.rc == 0

    - name: Compare versions and set update_needed
      ansible.builtin.set_fact:
        update_needed: "{{ current_version != latest_tag }}"
      when: is_installed.rc != 0

    - name: Debug current and latest versions
      ansible.builtin.debug:
        msg: "Current version: {{ current_version }}, Latest version: {{ latest_tag }}"
